# Customized for RL4CO
_target_: rl4co.utils.trainer.RL4COTrainer

default_root_dir: ${paths.output_dir} # Default path for logs and weights when no logger/ckpt_callback passed

gradient_clip_val: 1.0 # The value at which to clip gradients
accelerator: "auto" # Supports passing different accelerator types ("cpu", "gpu", "tpu", "hpu", "mps", "auto")
precision: "16-mixed" # Double precision (64, '64' or '64-true'), full precision (32, '32' or '32-true'), 16bit mixed precision (16, '16', '16-mixed') or bfloat16 mixed precision ('bf16', 'bf16-mixed'). Can be used on CPU, GPU, TPUs, or HPUs.

check_val_every_n_epoch: 1 # Perform a validation loop after every `N` training epochs.

deterministic: False # set True to to ensure deterministic results, makes training slower but gives more reproducibility than just setting seeds