# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: ${paths.output_dir}/tensorboard/
  name: null
  log_graph: False
  default_hp_metric: True # Enables a placeholder metric with key hp_metric when log_hyperparams is called without a metric
  prefix: ""
  version: null
